### ISSUE TITLE
Build steps

### ISSUE THREAD

**Issue by juniortada** [ZIM555/android_device_samsung_fortunave3g#1]
Hello, my name is Junior Tada from Brazil, can you help me to build CM 13 for this device?
I am use linux ubuntu 16.04 and install all need for android/cm build
I am follow Cyanogenmod guide, please tell me is correct:
create main folder - fortunave3g
In this folder:
create folder device/samsung/fortunave3g - clone this repository
git clone https://github.com/ZIM555/android_device_samsung_fortunave3g.git -b cm-13.0
create folder kernel/samsung/fortunave3g - clone your kernel repository
git clone https://github.com/ZIM555/android_kernel_samsung_fortunaxx3g.git -b cm-13.0
create foler  vendor/samsung/fortunave3g - clone your vendor repository
git clone https://github.com/ZIM555/android_vendor_samsung_fortunave3g.git -b cm-13.0
In main folder install repo and cyanogenmod source:
$ curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$ chmod a+x ~/bin/repo
set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
$ repo init -u https://github.com/CyanogenMod/android.git -b cm-13.0
$ repo sync
$ source build/envsetup.sh
$ breakfast fortunave3g
$ brunch fortunave3g

I am forgetting any step?
I want to contribute to the development but this is my first time for build android/cm system.

**Comment by ZIM555** [comment]
need only this
In main folder install repo and cyanogenmod source:
$ curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$ chmod a+x ~/bin/repo
set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
PATH="$HOME/bin:$PATH"
fi
$ repo init -u https://github.com/CyanogenMod/android.git -b cm-13.0
$ repo sync
$ source build/envsetup.sh
$ breakfast fortunave3g
$ brunch fortunave3g

**Comment by juniortada** [comment]
Thank you very much, i can build finally! 
Now I would like to help test and develop, i don't have many experience, this is my first android compile, but i would like to help. This device have xda topic forum or other forum?
How can i report issues and bugs ticket? 
I see you comment in this forum the news report (i read  with google translate)
http://4pda.ru/forum/index.php?showtopic=647754&st=5060
Thank you again!
